### ISSUE TITLE
Stop flink-sql-runner-dist from emitting an empty jar

### ISSUE THREAD

**Issue by robobario** [streamshub/flink-sql#24]
Currently the build produces the tarball but it also produces an empty jar we don't need.

```
[INFO] --- jar:3.4.1:jar (default-jar) @ flink-sql-runner-dist ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /home/robeyoun/development/upstream/flink-sql/flink-sql-runner-dist/target/flink-sql-runner-dist-0.0.1-SNAPSHOT.jar
[INFO] 
```

We should configure it to stop producing this jar.

**Comment by katheris** [comment]
@robobario were you planning to pick this up? If not I can pick it up

**Comment by robobario** [comment]
@katheris I did not plan to, go ahead!

**Comment by katheris** [comment]
Resolved by https://github.com/streamshub/flink-sql/pull/25
